<html>
    <head>
    	<title>ORDER DETAILS</title>
   </head>

   <body>
   	<h3> Dear <?php echo $ownername ;?>, </h3>
   	<p>Please find the attached shipping Label, invoice and image.</p>
   	<p>Click To Download Shipping Label.</p>
    <a href = "<?php echo $shippingpartner; ?>"> Download </a>
    <p>Click To Download Invoice.</p>
    <a href = "<?php echo $filename1; ?>"> Download </a>
    <p>Click To Download Image.</p>
    <a href = "<?php echo $image; ?>"> Download </a>
   	<p>To schedule a pick up, kindly send an email only to ops@buynbrag.com.</p>
   	<p>This is an autogenerated mail,Do not reply to this mail</p>
   	<p>Order Information is mentioned below</p>
    <p>Order ID:<?php echo $orderid;?></p>
    <p>Store Name:<?php echo $storename ;?></p>
    <p>Product Name:<?php echo $productname ;?> </p>
    <p>Product Code:<?php echo $productcode;?></p>
    <p>Payment Amount:<?php echo $paymentAmount ;?></p>
    <p>Payment Type:<?php echo $paymentType;?></p>
    <p>Buyer Name:<?php echo $Customername ;?></p>
    <p>Buyer Address:<?php echo $BuyerAddress ;?></p>
    <p>Buyer Mobile:<?php echo $BuyerMobile;?></p>
    <p>Processing Time:<?php echo $ProcessingTime;?></p>
    <p>Estimated Dispatch Date:<?php echo $Estimateddispatchtime;?></p>
   </body>
</html>